apiVersion: v1
kind: Secret
metadata:
  name: payments-api-secrets
  namespace: fcg-tech-fase-2
  labels:
    app: payments-api
type: Opaque
data:
  # Base64 encoded values - ALTERE EM PRODUÇÃO!
  # echo -n 'valor' | base64
  
  # Connection string do Postgres
  # Host=payments-db;Port=5432;Database=fcg_payments_db;Username=payments;Password=paymentspw
  # Host=postgres;Port=5432;Database=fcg_payments_db;Username=payments;Password=paymentspw
  ConnectionStrings__Default: SG9zdD1wb3N0Z3JlcztQb3J0PTU0MzI7RGF0YWJhc2U9ZmNnX3BheW1lbnRzX2RiO1VzZXJuYW1lPXBheW1lbnRzO1Bhc3N3b3JkPXBheW1lbnRzcHc=
  
  # RabbitMQ Host: rabbitmq
  RabbitMq__Host: cmFiYml0bXE=
  
  # RabbitMQ Username: admin
  RabbitMq__Username: YWRtaW4=
  
  # RabbitMQ Password: admin123
  RabbitMq__Password: YWRtaW4xMjM=